### PR TITLE
Update welcome.yml

### LINKED ISSUE #254: Remove link to CB-PASTAX project on welcome page

### PR DESCRIPTION
**Pull request by Tilmon**
* Close #254
* Relates to #249 

@kalashsinghal or @maurolepore please accept this change to remove the link from the welcome page. Thanks! @maurolepore will the change automatically be implemented in the user facing app or only in the tilt-staging app? If it's not automatically implemented in user facing app, what do we need to do to also implement it there? 

----

The whole game:

- [x] 1. Anne and Tilman create a PR from GitHub.
- [ ] 2. Kalash tests the app locally and merges the PR ([Why and how video](https://youtu.be/6vd8XqiqLHQ?si=e0ckfgVEDA3InszQ)).
- [ ] 3. Anne and Tilman validate the changes on staging.
- [ ] 4. Kalash creates a new release.
- [ ] 5. Everyone confirms the change is now in production.

### CODE REVIEW

**Comment by maurolepore** [comment]
FYI I updated the top comment. It now includes the valid keyword "close", expands the issue title (by starting the line with `* ...`)., and includes the practice checklist.

### Kalash

@kalashsinghal, I think updating snapshots is beyond the scope of what we're trying to achieve. 

It seems to me that the best use of Tilman's and Anne's time is not on the package-development side of things but in giving you the exact changes they want. Doing this themselves significantly reduces the communication time and increases the accuracy the changes they propose.

Measured in team-time the most efficient workflow will most likely be this:

* Tilman/Anne edit text directly on GitHub (no need to run anything).
* Kalash checkout the code locally, runs tests (updating snapshots as necessary), runs checks, deploys the app to see it still works fine, does any necessary change and leads any necessary discussion, and eventually merges the PR.

### Kalash and Tilman

Note what we're doing here maps to steps 1 and 2 in the checklist above. You may go through many cycles of 1-2 before you feel like you need a new release. At that point you move to 3. 

### Tilman

> Thanks! @maurolepore will the change automatically be implemented in the user facing app or only in the tilt-staging app? If it's not automatically implemented in user facing app, what do we need to do to also implement it there?

@Tilmon this will update only tilt-staging.

> A staging environment (stage) is a nearly exact replica of a production environment for software testing. Staging environments are used to test codes, builds and updates to ensure quality under a production-like environment before application deployment.

Updating the user-facing app automatically is too risky. It's quite likely for our intuition to suggest that a change is fine but unexpectedly break something of the app. For an example of this see why and how to test the app locally ([5' video](https://youtu.be/6vd8XqiqLHQ?si=e0ckfgVEDA3InszQ) in the tilt (unlisted) playlist -- linked under Resources in the https://bit.ly/offboarding-mauro).

**Comment by kalashsinghal** [comment]
> I think updating snapshots is beyond the scope of what we're trying to achieve. It seems to me that the best use of Tilman's and Anne's time is not on the package-development side of things but in giving you the exact changes they want.

Hi @maurolepore Thanks for your insight! I now have a better understanding on the complete workflow. I have seen your 10 mins video for moving the branch `release` to point to `main`. I have one question and one request:

1. What the are git commands `glol` and `gp` that you used in the video? I guess they are shortcuts, however I don't completely understand them. Therefore, please outline all the git commands without shortcuts! Thanks!
2. I tried to resolve the check fails after [updating the snapshots](https://github.com/2DegreesInvesting/tiltWebTool/pull/255/commits/74738444276c573455e7c5fad875207f10b48a4e) and [merging the main branch ](https://github.com/2DegreesInvesting/tiltWebTool/pull/255/commits/372ad98ad448a53a3179ac835bc269ca30c43563). However, I can see that the same snapshot test fails are appearing on github and not locally on my system. Do you know why is that? It seems a completely new issue to me. Is it because I am using an outdated package? Is yes, then which one?

**Comment by Tilmon** [comment]
hi @maurolepore thanks for the additional explanation of the workflow! And @kalashsinghal thanks for biting the bullet and testing everything out :) 

cc' @AnneSchoenauer just FYI, we are testing the workflow

**Comment by Tilmon** [comment]
And @maurolepore it's really insane how many guidance videos you created for us!!

**Comment by maurolepore** [comment]
@kalashsinghal RE "shortcuts", here are the two  aliases you mention:

```
➜  ~ alias glol
glol='git log --graph --pretty="%Cred%h%Creset -%C(auto)%d%Creset %s %Cgreen(%ar) %C(bold blue)<%an>%Creset"'
➜  ~ alias gp
gp='git push'
```

And here are all my aliases: https://github.com/maurolepore/dotfiles/blob/main/aliases.zsh

**Comment by maurolepore** [comment]
@kalashsinghal RE the snapshots, it's weird the snapshots I see in this PR are unrelated to the change that Tilman did, and I can't reproduce your problem -- see https://github.com/2DegreesInvesting/tiltWebTool/pull/256.

So yeah, it seems like your local environment is somehow different. I suggest:

- [ ] Ensure your main branch is up to date: `git checkout main && git pull`
- [ ] Ensure all your dependcenties are up to date: `pak::pak()`.
- [ ] Ensure all your snapshots are up to date: `devtools::test()`
- [ ] Ensure R CMD check passes cleanly: `devtools::check()`.

Then checkout this PR and try again.

**Comment by kalashsinghal** [comment]
@maurolepore Thanks for your insight! One of the package on my system was not updated. I have resolved the issue, and I will now merge this PR. :)

**Pull request merged**
