### PR TITLE
Update welcome.yml

### LINKED ISSUE #252: Test PR: Tilman adds space to webtool text

### PR DESCRIPTION
**Pull request by Tilmon**
* Close #252

Hi @kalashsinghal please review my PR to test the workflow @maurolepore was suggesting :) 

----

The whole game:

- [x] Anne and Tilman create a PR from GitHub.
- [ ] Kalash tests the app locally and merges the PR ([Why and how - 4'30" video](https://youtu.be/6vd8XqiqLHQ?si=e0ckfgVEDA3InszQ)).
- [ ] Anne and Tilman validate the changes on staging.
- [ ] Kalash creates a new release.
- [ ] Everyone confirms the change is now in production.

### CODE REVIEW

**Review by kalashsinghal — APPROVED** [review]
LGTM!

Its great to see the pull request from you Tilman :D. Congrats!

**Comment by maurolepore** [comment]
* Relates to #249 

For convenience I pasted the checklist at the tip and checked @Tilmon's action.

## Tilman

@Tilmon, good on you for linking the related issue. What you missed there was a keyword so that GitHub closes the linked issue automatically. There are a few [valid keywords](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests) but the only one you need to remember is "close". Also remember that if you start a line with `* ` then GitHub automatically expands the issue number to show the title. 

So this

```
* Close #252
```

Becomes this:

* Close #252

But this

```
# 252
```

Besomes this

#252 

## Kalash

@kalashsinghal please continue and let me know your questions so I can respond before the end of this week. Note the 5' linked video (see checklist above) on how and why to test the app locally.

**Comment by kalashsinghal** [comment]
@maurolepore I tested the app locally and it works fine. I tested it both on product and company level as suggested by you in the 5 min video. Therefore, I will merge this PR.

image

**Comment by kalashsinghal** [comment]
@Tilmon @AnneSchoenauer Please validate the changes on staging so that I can create a new release.

**Pull request merged**
